---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: projets
  label: Projets
  create: all
  match: "**/*"
- type: directory
  path: articles
  label: Articles
  create: all
  match: "**/*"
- type: directory
  path: cours
  label: Cours
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
